name: Create Changelog
on:
  pull_request:
    branches:
      - main

jobs:
  Create-changelog:
    if: github.repository == 'pagefaultgames/pokerogue'
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-deps

      - name: Generate Changelog
        run: pnpm changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          PR_BRANCH: ${{ github.event.pull_request.head.label }}
