name: Post Release Deleted
on:
  delete:

jobs:
  # Set the BETA_DEPLOY_BRANCH variable to beta when a release branch is deleted
  update-release-var:
    if: github.repository == 'pagefaultgames/pokerogue' && github.event.ref_type == 'branch' && github.event.ref == 'release'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Set BETA_DEPLOY_BRANCH to beta
        run: GITHUB_TOKEN="${{ secrets.RW_VARS_PAT }}" gh variable set BETA_DEPLOY_BRANCH --body "beta" --repo "pagefaultgames/pokerogue"